# Generated by Django 4.1.1 on 2022-09-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
