# Generated by Django 4.1.1 on 2022-09-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pictures_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=10)),
                ('picture', models.CharField(default='', max_length=70)),
                ('quantity', models.CharField(default='', max_length=70)),
                ('date', models.CharField(default='', max_length=200)),
                ('time', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=10)),
                ('lname', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
