# Generated by Django 4.1.1 on 2022-09-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pictures_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='name',
        ),
    ]
