# Generated by Django 4.1.1 on 2022-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_title_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='categories',
            field=models.CharField(default='', max_length=100),
        ),
    ]
