# Generated by Django 4.1.1 on 2022-09-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orders_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
